on:
  push:
    branches:
      - main

jobs:
  updateAuthors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} â€º AUTHOR

      - name: Create and push branch
        run: |
          git config --global user.name "${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          git config --global user.email "${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
          git checkout -b auto-pr-branch
          git add AUTHOR
          git commit -m "Update author information"
          git push origin auto-pr-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: "auto-pr-branch"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation
          title: "demo for auto pr"
          delete-branch: true
